networks:
  fanera:
    name: fanera

services:
  nginx:
    container_name: fanera_nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./www:/var/www
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fanera
    depends_on:
      - php
  php:
    container_name: fanera_php
    build: docker/images/php83fpm
    volumes:
      - ./www:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - fanera
    depends_on:
      - mysql
  mysql:
    container_name: fanera_mysql
    image: mysql:5.7
    volumes:
      - ./www:/var/www/
      - ./docker/mysql-data:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_USER=fanera
      - MYSQL_PASSWORD=fanera
      - MYSQL_ROOT_PASSWORD=fanera
      - MYSQL_DATABASE=fanera
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    networks:
      - fanera
  phpmyadmin:
    container_name: fanera_phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - 1500:80
    environment:
      - PMA_HOST=fanera_mysql
      - UPLOAD_LIMIT=100M
      - MEMORY_LIMIT=256M
      - MAX_EXECUTION_TIME=300
    networks:
      - fanera
    depends_on:
      - mysql